<html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Simulador de Energia Solar</title>
</head>
<body>
  <h1>Simulador de Energia Solar</h1>

  <form id="simulador">
    <label for="horasDeLuzSolar">Horas de Luz Solar por Dia:</label>
    <input type="number" id="horasDeLuzSolar" required>
    <br><br>

    <label for="potenciaDoPainel">Potência do Painel Solar (em watts):</label>
    <input type="number" id="potenciaDoPainel" required>
    <br><br>

    <label for="eficienciaDoPainel">Eficiência do Painel Solar (em decimal):</label>
    <input type="number" id="eficienciaDoPainel" step="0.01" min="0" max="1" required>
    <br><br>

    <label for="quantidadeDias">Quantidade de Dias:</label>
    <input type="number" id="quantidadeDias" required>
    <br><br>

    <button type="button" onclick="calcularEnergia()">Calcular Energia Gerada</button>
  </form>

  <p id="resultado"></p>

  <script>
    function calcularEnergia() {
      const horasDeLuzSolar = parseFloat(document.getElementById('horasDeLuzSolar').value);
      const potenciaDoPainel = parseFloat(document.getElementById('potenciaDoPainel').value);
      const eficienciaDoPainel = parseFloat(document.getElementById('eficienciaDoPainel').value);
      const quantidadeDias = parseInt(document.getElementById('quantidadeDias').value);

      const energiaDiaria = horasDeLuzSolar * potenciaDoPainel * eficienciaDoPainel / 1000; // em kWh
      const energiaTotal = energiaDiaria * quantidadeDias;

      document.getElementById('resultado').innerHTML = `Durante ${quantidadeDias} dias, o painel solar de ${potenciaDoPainel} watts gerará aproximadamente ${energiaTotal} kWh de energia.`;
    }
  </script>
</body>
</html>
